### ISSUE TITLE
Fatal error when WooCommerce is activated (Comments)

### ISSUE THREAD

**Issue by Mahjouba91** [joshuadavidnelson/disable-blog#11]
Hello,

First, my website is on last version of WordPress, your plugin and WooCommerce.

I tried the plugin on my private website and show me a PHP fatal error on activation about woocommerce comments.

I spoted where the bug come from admin/class-disable-blog-admin.php :

```php
public function filter_wp_count_comments( $comments, $post_id ) {

		// if this is grabbing all the comments, filter out the 'post' comments.
		if( 0 == $post_id )
			$comments = $this->get_comment_counts();

		// If we filtered it above, it needs to be an object, not an array.
		if( ! empty( $comments ) ) {
            $comments = (object) $comments;
        }

		return $comments;
	}
```

It bugs in the casting operation (array to object).

Here is the fatal error :
`Fatal error: Uncaught Error: Cannot use object of type stdClass as array in \wp-content\plugins\woocommerce\includes\class-wc-comments.php:272 Stack trace: #0 \wp-includes\plugin.php(235): WC_Comments::wp_count_comments(Object(stdClass), 0) #1 wp-includes\comment.php(1113): apply_filters('wp_count_commen...', Object(stdClass), 0) #2 wp-admin\menu.php(72): wp_count_comments() #3 wp-admin\admin.php(138): require('C:\\xampp\\htdocs...') #4 wp-admin\plugins.php(10): require_once('C:\\xampp\\htdocs...') #5 {main} thrown in \wp-content\plugins\woocommerce\includes\class-wc-comments.php on line 272`

**Comment by joshuadavidnelson** [comment]
@Mahjouba91 Thanks for reporting this error. I haven't run tests with WooCommerce, I'll track down the issue and fix it.

**Comment by joshuadavidnelson** [comment]
I'm not able to replicate the issue yet, but I think I see the problem.

Ultimately the `$comments` variable needs to be delivered as an object (see the return in [wp_count_comments](https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/comment.php#L1102)), but it looks like [WooCommerce is filtering the object](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-comments.php#L43) after disable-blog filters it. I'll update the hook priority in the disable blog plugin to occur later, which should resolve the error.

I'm swamped and working overtime this weekend, but I'll try to get this updated and test soon. In the meantime, you should be able to resolve it by changing the priority from 10 to 100 [here](https://github.com/joshuadavidnelson/disable-blog/blob/master/includes/class-disable-blog.php#L250).

**Comment by joshuadavidnelson** [comment]
Seems like returning an array will be the better route to go. See the [Issue-11 branch](https://github.com/joshuadavidnelson/disable-blog/tree/issue-11) and let me know if that fixes the issue. I'm testing a few other things related to the comment counts before I issue a new release.

**Comment by joshuadavidnelson** [comment]
Alright, looking back at it, I think the reason I can't replicate the error is I assumed the most recent version. WooCommerce should be setting this variable to an array (or checking it is an array) prior to using it as one since other plugins/themes can filter it and have to return it as an object.

It looks like they[ committed a change that does that in July](https://github.com/woothemes/woocommerce/commit/7318235f5822066ee0f5935366a7f959369ebbca). Are you running the most recent version of WooCommerce (2.6.4)? Because there is a blank link in class-wc-comments.php line 272, referenced in your error. See if updating WooCommerce solves the issue.

I'll look back at their releases to when this changed and put in some backwards compatibility in my plugin for the older versions of WooCommerce if that's the case.

**Comment by Mahjouba91** [comment]
Oh I'm sorry, I gave you wrong informations, my WooCommerce version was not updated, I'm still on 2.5 branch. I hope there will be a way to ensure backward compa with all recent versions to avoid fatal error like that.

Thanks for the review ;)

**Comment by joshuadavidnelson** [comment]
@Mahjouba91 Yes, the [issue branch](https://github.com/joshuadavidnelson/disable-blog/tree/issue-11) appears to work on your version, giving backward compatibility for WooCommerce. I'll merge into production and release an update sometime soon, within the week.

**Comment by Mahjouba91** [comment]
Your patch seems good, I really apreciate your work thank you ;)

**Comment by joshuadavidnelson** [comment]
Finally got around to updating the repo (here and on WP.org). Let me know if there are any other issues!
