### ISSUE TITLE
Remove the comments in the backend

### ISSUE THREAD

**Issue by iannacone** [joshuadavidnelson/disable-blog#15]
For people who don't need the comments in the backend just add this in the `functions.php`

```php
function remove_menu_comments($pages) {
	$pages[] = 'edit-comments.php';
	return $pages;
}
add_filter('dwpb_menu_pages_to_remove', 'remove_menu_comments');
```

**Comment by iannacone** [comment]
plus:
```php
function disable_comments($post_types_with_feature) {
	$post_types_with_feature = false;
	return $post_types_with_feature;
}
add_filter('dwpb_post_types_supporting_comments', 'disable_comments');
```

**Comment by joshuadavidnelson** [comment]
Hey there @iannacone, thanks for these examples!

**Comment by bueltge** [comment]
There is more a to do to remove comments about the installation as only the back end page, see https://github.com/bueltge/remove-comments-absolutely that remove all areas for comments context.
