### ISSUE TITLE
redirect_admin_pages() may redirect even if it shouldn’t (multisite)

### ISSUE THREAD

**Issue by KittMedia** [joshuadavidnelson/disable-blog#17]
I have a multisite with a custom plugin, that adds an own network option page. By updating these settings, the form action is set to `/wp-admin/network/edit.php?action=my_action` to store the settings via `network_admin_edit_my_action`.

Unfortunately, this will trigger the redirect_admin_pages() function in the Disable_Blog_Admin class and redirect to `admin_url( '/edit.php?post_type=page' )` before my hook `network_admin_edit_my_action` fires.

This will always be the case for network option updates as long as the Disable Blog plugin is active network-wide or for the first blog in a multisite.

A check for multisite should be added here and then disable the redirection of the `redirect_admin_pages()` on network option updates.

**Comment by joshuadavidnelson** [comment]
@KittMedia Just saw this pop up on my notifications! Thanks for posting this, I'll get a solution together as soon as possible.

**Comment by joshuadavidnelson** [comment]
Hey @KittMedia - I think the solution in #21 should solve your problem, let me know if you have a chance to test it out. I'm working on a few other things, but should be getting an update out with this change and some other items later this week or next.

**Comment by KittMedia** [comment]
Thank you, I will take a look into it. However, due to the Corona crisis, I cannot do it currently.

**Comment by joshuadavidnelson** [comment]
No worries, of course! Hope you're doing alright. Let me know if you have any other issues with the plugin.

**Comment by KittMedia** [comment]
Seems fine to me! Thank you. :)
