### ISSUE TITLE
Add 3 basic zero-coverage tests to CI

### ISSUE THREAD

**Issue by szepeviktor** [joshuadavidnelson/disable-blog#24]
1. syntax check
1. coding standard
1. static analysis

What do you think?

**Comment by joshuadavidnelson** [comment]
Hey @szepeviktor - thanks for the PR and this suggestion. I'd love to get some testing setup, I've just been swamped with many other things, but it's been on my list of "like to haves" for a while. I don't have any solid eta or roadmap for it at the moment.

**Comment by szepeviktor** [comment]
The only thing remaining is following WPCS.

What do you think about it?

**Comment by joshuadavidnelson** [comment]
That's awesome, I really appreciate the contribution! I'm all for WPCS checks, too.

**Comment by szepeviktor** [comment]
Done.

Two TODOs for **you**

1. reach Level max in PHPStan
1. use all rules of WPCS
