### ISSUE TITLE
Undefined variable: current_url in [...]/disable-blog/public/class-disable-blog-public.php on line 127

### ISSUE THREAD

**Issue by chesio** [joshuadavidnelson/disable-blog#29]
I get the PHP Notice with version 0.4.7.

The problem seems to be that the variable is initially [declared and used](https://github.com/joshuadavidnelson/disable-blog/blob/master/public/class-disable-blog-public.php#L112-L113) with a typo in it, but later on [referenced](https://github.com/joshuadavidnelson/disable-blog/blob/master/public/class-disable-blog-public.php#L127) without a typo.

**Comment by joshuadavidnelson** [comment]
Hey @chesio! Thanks for catching this and the PR.

I'll get this merged into a release this week.
