### ISSUE TITLE
Crashes php5-fpm

### ISSUE THREAD

**Issue by shawnhooper** [joshuadavidnelson/disable-blog#4]
Hi Joshua,

Installed the disable-wordpress-blog plugin on a site I'm building, and came across a very strange bug.  The server is running NGINX + MariaDB + PHP5-FPM + Varnish cache.  

I can install your plugin and activate it, and move around wp-admin.   As soon as I visit the front-end of the site, it crashes. To get the site back up, I need to restart PHP5-FPM and disable your plugin.  I can reproduce this over and over.

I'm curious if you've ever heard of this happening, as I haven't run into this problem with any other plugin.

Thanks in advance.

**Comment by joshuadavidnelson** [comment]
Wow, no, I haven't heard of that happening before. This plugin was created in two major coding sessions and still needs some refining, hence the "beta" notice. I've been swamped with client work and haven't had a chance to circle back for testing further. Any chance you have any error logs on the failure?

Without more information it will be hard to guess, but crashing PHP5-FPM might happen if the plugin was causing a heavy load on the server - I haven't done any speed tests on this plugin yet. It could be a condition to the setup of your site, perhaps an infinite loop or something similar dragging it down.

I don't have the ability to replicate that environment at the moment. If you're up for it, I'd love help tracking down the issue. I'd recommend commenting out all the main class `init()` function, verify it works without crashing, and then start adding each action hook back in to test each one. 

Appreciate the heads up on this issue!

**Comment by shawnhooper** [comment]
I've narrowed it down to this hook:

// Redirect Single Posts
add_action( 'template_redirect', array( $this, 'redirect_posts' ) );

If I comment it out, everything works as expected.  

Will do some more debugging.

**Comment by joshuadavidnelson** [comment]
Ah, nice work! I had a suspicion that was the culprit. I think the redirect of the `home_url` is the likely issue - it's creating a loop, redirect back to the home_url. It probably only works correctly if the post page is _not_ the home page. It should probably have two checks: first, make sure the home url and the front page url are not the same if it redirects the blog page (the intent of that redirect), and a final check that the current page is not the same as the redirect url (to avoid loops).

For a site that's not set up to have a static front page, we might have to expand the redirect to either redirect to a page or throw a 404 until the static front page is set.

**Comment by shawnhooper** [comment]
Aah, just read your most recent comment.  Didn't see that before I submitted my PR.  I hadn't thought of the home page being the posts page... (as it isn't on the particular site I'm working on) so it does need some more logic.  

A 404 is that scenario would work, but could confuse a site owner really quickly if they don't know the URL to wp-login.php  (I'm sure there are some out there who use the Log In link in the default Meta sidebar).  

Have to give that some thought.

**Comment by joshuadavidnelson** [comment]
Yea, #6 would solve the one issue, but you're right - it's not a complete solution. I'm not 100% sure the best user experience for this situation, open to ideas. I'll do some thinking on it. For now, your fix could be a temporary solution to avoid the critical loop/failure.

**Comment by joshuadavidnelson** [comment]
There's actually a function hooked into `admin_init` to set the static front page setting, if it's not set. It sets the value to 0. I think it should bail on the redirect if there is not a static front page, and use that option to set the redirect url if there is one. See 0d7de6015089a35336fa31dbfb11592776e827f0 and let me know if that fixes the issue for you.

**Comment by joshuadavidnelson** [comment]
Just released a new version, I think this handles the issue you were having (as well as a fix for another issue). Let me know if it doesn't work. See f5b83e9338dd09e1e0846a46290085c72d9ff29a

**Comment by joshuadavidnelson** [comment]
@shawnhooper Just wanted to check in on this one, where you able to get my fix to work for you? I believe this issue is resolved with the newest version. Let me know if not!

**Comment by joshuadavidnelson** [comment]
@shawnhooper I'm going to close this issue, since I'm guessing you've either moved on or the update fixed the issue. Feel free to reach out if there are any other issues or follow up needed on this one. Cheers!
