### ISSUE TITLE
Problems with the WordPress-app

### ISSUE THREAD

**Issue by z1tr0t3c** [joshuadavidnelson/disable-blog#50]
Hello,

I like your plugin and used it on a wp-install without the need for a blog, than I wanted to edit some pages with the WordPress-app and the login failed.
Is there a possibility to get the wp-app back working again and using the plugin.
I really only want to edit some pages on the go with the app ;)

Thank you and best regards,
Falk

**Comment by z1tr0t3c** [comment]
![image](https://user-images.githubusercontent.com/23585913/120915889-a03aa200-c6a6-11eb-9377-be056c842f86.png)

**Comment by joshuadavidnelson** [comment]
Hey there, thanks for reaching out! Sorry you're experiencing this issue. The issue is related to the xmlrpc methods being used by that app, which are disabled by the plugin. I'll take a look as soon as possible and follow up sometime this week.

**Comment by z1tr0t3c** [comment]
Hi, can you provide me any new information?

**Comment by joshuadavidnelson** [comment]
Hey @z1tr0t3c - version 0.5.0 now supports disabling and modifying the methods via a filter:

To stop the plugin from removing any xmlrpc methods from WordPress, drop `add_filter( 'dwpb_disabled_xmlrpc_methods', '__return_false' );` into your functions file or a custom plugin file. 

You can also use this filter to modify the methods being removed:

```
add_filter( 'dwpb_disabled_xmlrpc_methods', 'issue_50_example_filter_methods', 10, 1 );
/**
 * Filter the methods being disabled by the plugin.
 *
 * Return false to disable this functionality entirely and keep all methods in place.
 *
 * @since 0.5.0
 * @param array $methods_to_remove an array of all the XMLRPC methods to disable.
 * @return array|bool
 */
function issue_50_example_filter_methods( $methods_to_remove ) {

	// custom logic here to modify the array

	return $methods_to_remove;

}
```

**Comment by z1tr0t3c** [comment]
Thank you!
