### ISSUE TITLE
Filter dwpb_xmlrpc_methods_to_remove not working

### ISSUE THREAD

**Issue by z1tr0t3c** [joshuadavidnelson/disable-blog#55]
Hey,

I've added the filter from https://github.com/joshuadavidnelson/disable-blog/issues/50 to my custom-plugin, but I still can't manage my pages with the wordpress mobile app and the disable-blog plugin active.
On refreshing the pages list I get the same error message and setup of the wp site is also only possible if the plugin is disabled.

**Comment by joshuadavidnelson** [comment]
Hey @z1tr0t3c - Sorry to hear you're having trouble with this! Thanks for creating a new issue.

Can you clarify what you mean by "setup of the wp site is also only possible if the plugin is disabled" - do you mean that in the context of the WP app or is that a broader issue impacting your site outside of the WP app? 

I'll double check this filter, see if I can replicate the xmlrpc/WP app issue using v0.5.0, and follow up as I'm able.

**Comment by z1tr0t3c** [comment]
Yes, I meant this in the context of the wordpress mobile app.

**Comment by joshuadavidnelson** [comment]
Looks like I had the incorrect filter name, it should be `dwpb_disabled_xmlpc_methods` - apologies.

I'll need to update readmes and such, but I've updated [the snippet in the original issue](https://github.com/joshuadavidnelson/disable-blog/issues/50#issuecomment-1098558321). 

Let me know if that does/doesn't work.

**Comment by z1tr0t3c** [comment]
With the filter `dwpb_disabled_xmlrpc_methods` it worked.
Thanks!
