### ISSUE TITLE
Full Site Editing Compatibility

### ISSUE THREAD

**Issue by joshuadavidnelson** [joshuadavidnelson/disable-blog#60]
Per [this support forum post](https://wordpress.org/support/topic/breaks-site-editor-full-site-editing-fse-page-content/), removing post related blocks breaks Full Site Editing where those blocks are used for other post types (including pages!). Future release should include some method to "disable posts" while supporting these blocks.

**Comment by ligne13** [comment]
I also noticed this bug today when updating to 0.5.1. It works with 0.5.0.

thanks.
