### ISSUE TITLE
Deletion failed: on WordPress Version 6.1

### ISSUE THREAD

**Issue by spaelectronics** [joshuadavidnelson/disable-blog#61]
When I try to delete this plugin, it fails to delete. 
It shows "Deletion failed:" at the top of the screen.

**Comment by joshuadavidnelson** [comment]
Hey @spaelectronics - this is likely an issue specific to your WordPress install or site, host, etc. You can try removing the files via FTP ([see this article](https://kinsta.com/blog/uninstall-wordpress-plugin/#uninstall-wordpress-plugin-ftp)).
